(() => {
"use strict";
const state={messages:[],selectedId:null,filter:"all",search:""};
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const initials=n=>String(n||"A").trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"A";
function date(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat(undefined,{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}
function cls(s){return `status-${String(s||"new").toLowerCase()}`}
function label(s){return String(s||"new").toUpperCase()}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),2800)}
async function api(url,opt={}){const r=await fetch(url,{credentials:"same-origin",...opt,headers:{...(opt.body?{"Content-Type":"application/json"}:{}),...(opt.headers||{})}});if(r.status===401){location.href="/";throw Error("Authentication required.")}if(r.status===403){document.body.innerHTML='<div style="min-height:100vh;display:grid;place-items:center;background:#030706;color:#fff;font-family:Inter,sans-serif;text-align:center"><div><h1 style="font-family:Rajdhani;color:#ffd54f">ADMIN ACCESS REQUIRED</h1><p style="color:#999">Your account does not have administrator privileges.</p><a href="/" style="color:#00d9ff">Return to login</a></div></div>';throw Error("Administrator access required.")}let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.detail||`Request failed (${r.status})`);return d}
function counts(ms){return{total:ms.length,new:ms.filter(x=>x.status==="new").length,read:ms.filter(x=>x.status==="read").length,replied:ms.filter(x=>x.status==="replied").length,closed:ms.filter(x=>x.status==="closed").length}}
function setCounts(c){$("countTotal").textContent=c.total||0;$("countNew").textContent=c.new||0;$("countRead").textContent=c.read||0;$("countReplied").textContent=c.replied||0;$("countClosed").textContent=c.closed||0;$("sidebarNewCount").textContent=c.new||0}
function filtered(){const q=state.search.trim().toLowerCase();return state.messages.filter(m=>(state.filter==="all"||m.status===state.filter)&&(!q||[m.name,m.email,m.subject,m.message].join(" ").toLowerCase().includes(q)))}
function render(){const list=$("messageList"),ms=filtered();$("resultCount").textContent=`${ms.length} request${ms.length===1?"":"s"}`;if(!ms.length){list.innerHTML='<div class="empty"><div>◌</div><h3>No requests found</h3><p>Try another filter or search.</p></div>';return}list.innerHTML=ms.map(m=>`<article class="message-item ${Number(m.id)===state.selectedId?"selected":""}" data-id="${Number(m.id)}"><div class="message-top"><span class="sender-name">${esc(m.name||"Unknown sender")}</span><span class="status-pill ${cls(m.status)}">${esc(label(m.status))}</span></div><div class="message-subject">${esc(m.subject||"No subject")}</div><p class="message-preview">${esc(m.message||"")}</p><div class="message-bottom"><span class="message-date">${esc(date(m.created_at))}</span><span class="message-date">#${esc(m.id)}</span></div></article>`).join("");list.querySelectorAll(".message-item").forEach(x=>x.onclick=()=>select(Number(x.dataset.id)))}
function select(id){const m=state.messages.find(x=>Number(x.id)===id);if(!m)return;state.selectedId=id;$("detailEmpty").classList.add("hidden");$("detailContent").classList.remove("hidden");$("detailSubject").textContent=m.subject||"No subject";$("detailStatus").textContent=label(m.status);$("detailStatus").className=`status-pill ${cls(m.status)}`;$("detailAvatar").textContent=initials(m.name);$("detailName").textContent=m.name||"Unknown sender";$("detailEmail").textContent=m.email||"No email";$("detailEmail").href=m.email?`mailto:${encodeURIComponent(m.email)}`:"#";$("detailId").textContent=`#${m.id}`;$("detailDate").textContent=date(m.created_at);$("detailMessage").textContent=m.message||"";$("statusSelect").value=m.status||"new";$("detailNotice").textContent="";$("detailNotice").className="";render()}
async function load(preferred=state.selectedId){const d=await api("/api/admin/messages");state.messages=Array.isArray(d.messages)?d.messages:[];setCounts(d.counts||counts(state.messages));render();if(preferred!=null&&state.messages.some(x=>Number(x.id)===Number(preferred)))select(Number(preferred));else if(state.selectedId!=null){state.selectedId=null;$("detailEmpty").classList.remove("hidden");$("detailContent").classList.add("hidden")}}
async function save(){if(state.selectedId==null)return;const b=$("saveStatusBtn"),n=$("detailNotice"),status=$("statusSelect").value;b.disabled=true;b.textContent="SAVING...";n.textContent="";n.className="";try{const d=await api(`/api/admin/messages/${state.selectedId}`,{method:"PATCH",body:JSON.stringify({status})});const i=state.messages.findIndex(x=>Number(x.id)===Number(d.message.id));if(i>=0)state.messages[i]=d.message;setCounts(counts(state.messages));select(Number(d.message.id));n.textContent=`Status updated to ${label(status)}.`;n.className="success";toast(`Request #${d.message.id} marked ${label(status)}.`)}catch(e){n.textContent=e.message;n.className="error"}finally{b.disabled=false;b.textContent="SAVE STATUS"}}
async function init(){try{const me=await api("/api/auth/me"),u=me.user||{};if(String(u.role||"").toLowerCase()!=="administrator")throw Error("Administrator access required.");$("adminName").textContent=u.name||u.login||"Administrator";$("adminRole").textContent=u.role||"Administrator";$("userAvatar").textContent=initials(u.name||u.login);await load()}catch(e){console.error(e);toast(e.message||"Unable to load admin console.")}
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.filter=b.dataset.filter||"all";render()});$("searchInput").oninput=e=>{state.search=e.target.value||"";render()};$("saveStatusBtn").onclick=save;$("refreshBtn").onclick=async()=>{try{await load(state.selectedId);toast("Inbox refreshed.")}catch(e){toast(e.message)}};$("logoutBtn").onclick=async()=>{try{await api("/api/auth/logout",{method:"POST"})}finally{location.href="/"}}}
document.addEventListener("DOMContentLoaded",init);
})();
