const API_BASE_URL="http://localhost:8000/api";
const $=id=>document.getElementById(id),N=x=>Number.isFinite(Number(x))?Number(x):null,pct=x=>N(x)===null?"—":`${N(x).toFixed(2)}%`;
async function api(path,opts={}){const r=await fetch(API_BASE_URL+path,{...opts,headers:{Accept:"application/json","Content-Type":"application/json",...(opts.headers||{})}});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.status===204?{}:r.json()}
function fill(id,values,first){const s=$(id);s.innerHTML=`<option value="">${first}</option>`;(values||[]).forEach(v=>{const val=typeof v==="object"?(v.value??v.id??v.name):v;if(val===undefined)return;const o=document.createElement("option");o.value=val;o.textContent=typeof v==="object"?(v.label??v.name??val):val;s.appendChild(o)})}
function overview(d){const x=d.summary||d||{};$("reportCount").textContent=x.available_reports??x.report_count??"—";$("cleanAcc").textContent=pct(x.robust_clean_accuracy);$("robustAsr").textContent=pct(x.mean_robust_asr);$("gap").textContent=x.mean_gap!==undefined?`${Number(x.mean_gap).toFixed(2)} pp`:"—";$("source").textContent=x.source||"Backend";$("summarySource").textContent=x.source||"Backend"}
function summary(d){const x=d.summary||d||{};const box=$("summary");const lead=x.lead||x.executive_summary||x.description;const items=x.highlights||x.key_points||[];if(!lead&&!items.length){box.innerHTML='<div class="empty">No executive summary returned.</div>';return}box.innerHTML=`${lead?`<div class="summary-lead">${lead}</div>`:""}${items.length?`<div class="summary-items">${items.map(i=>`<div class="summary-item"><b>${i.type??"RESULT"}</b><strong>${i.title??i.name??"Finding"}</strong><p>${i.description??i.message??""}</p></div>`).join("")}</div>`:""}`}
function artifacts(d){const a=Array.isArray(d)?d:(d.artifacts||d.data||d.results||[]),box=$("artifacts");box.innerHTML=a.length?a.map(x=>`<div class="artifact"><div><b>${x.name??x.filename??"Report artifact"}</b><small>${x.description??x.path??""}</small></div><span class="state">${x.status??"AVAILABLE"}</span></div>`).join(""):'<div class="empty">No report artifacts returned.</div>'}
function metrics(d){const a=Array.isArray(d)?d:(d.metrics||d.data||d.results||[]),body=$("metrics");body.innerHTML="";$("rowCount").textContent=`${a.length} rows`;if(!a.length){body.innerHTML='<tr><td colspan="6"><div class="empty">No metrics returned.</div></td></tr>';return}a.forEach(x=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${x.metric??x.name??"—"}</td><td>${x.baseline!==undefined?pct(x.baseline):"—"}</td><td>${x.robust!==undefined?pct(x.robust):"—"}</td><td>${x.delta!==undefined?`${Number(x.delta).toFixed(4)}`:"—"}</td><td>${x.unit??"%"}</td><td>${x.source??"Backend"}</td>`;body.appendChild(tr)})}
function methodology(d){const a=Array.isArray(d)?d:(d.items||d.config||d.data||[]),box=$("methodology");if(Array.isArray(a)&&a.length){box.innerHTML=a.map(x=>`<div class="method"><b>${x.label??x.key??"CONFIG"}</b><strong>${x.value??"—"}</strong></div>`).join("");return}if(a&&typeof a==="object"){box.innerHTML=Object.entries(a).map(([k,v])=>`<div class="method"><b>${k}</b><strong>${typeof v==="object"?JSON.stringify(v):v}</strong></div>`).join("")}else box.innerHTML='<div class="empty">No configuration returned.</div>'}
function checks(d){const a=Array.isArray(d)?d:(d.checks||d.data||[]),box=$("checks");box.innerHTML=a.length?a.map(x=>`<div class="check ${x.status==="warning"?"warn":""}"><i></i><div><b>${x.name??x.check??"Artifact check"}</b><small>${x.message??x.description??x.status??""}</small></div></div>`).join(""):'<div class="empty">No artifact checks returned.</div>'}
function findings(d){const a=Array.isArray(d)?d:(d.findings||d.insights||d.data||[]),box=$("findings");box.innerHTML=a.length?`<div class="finding-grid">${a.map(x=>`<div class="finding"><b>${x.type??"FINDING"}</b><strong>${x.title??x.name??"Evidence note"}</strong><p>${x.description??x.message??""}</p></div>`).join("")}</div>`:'<div class="empty">No report findings returned.</div>'}
async function load(){
 const calls=[["/reports/summary",overview],["/reports/executive-summary",summary],["/reports/artifacts",artifacts],["/reports/metrics",metrics],["/reports/methodology",methodology],["/reports/checks",checks],["/reports/findings",findings],["/reports/options",d=>{const x=d.options||d||{};fill("reportType",x.types||x.report_types||[],"Select report type");fill("scope",x.scopes||[],"Select evaluation scope");fill("version",x.versions||[],"Latest")}]];
 let ok=0;for(const [p,f] of calls){try{f(await api(p));ok++}catch(e){}}
 $("api").classList.toggle("online",ok>0);$("api").classList.toggle("offline",ok===0);$("apiText").textContent=ok?"API ONLINE":"API OFFLINE";$("apiDetail").textContent=ok?`${ok}/${calls.length} report endpoints responding`:"Report endpoints unavailable";$("liveText").textContent=ok?"REPORT ENGINE READY":"BACKEND UNAVAILABLE";$("liveDetail").textContent=ok?"Dynamic report data loaded":"Waiting for FastAPI";$("updated").textContent=ok?`Updated ${new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"})}`:"Not loaded"
}
async function generate(){
 const body={report_type:$("reportType").value,scope:$("scope").value,format:$("format").value,version:$("version").value||"latest"};if(!body.report_type){$("generationText").textContent="Select a report type first.";$("generationState").textContent="INPUT REQUIRED";return}
 $("generationText").textContent="Submitting report generation job…";$("generationState").textContent="RUNNING";
 try{const r=await api("/reports/generate",{method:"POST",body:JSON.stringify(body)});$("generationText").textContent=r.message||r.job_id||"Report generation started.";$("generationState").textContent=r.status?String(r.status).toUpperCase():"SUBMITTED"}catch(e){$("generationText").textContent="Report generation endpoint unavailable.";$("generationState").textContent="UNAVAILABLE"}
}
async function preview(){const body={report_type:$("reportType").value,scope:$("scope").value,format:"html",version:$("version").value||"latest"};try{const r=await api("/reports/preview",{method:"POST",body:JSON.stringify(body)});if(r.url)window.open(r.url,"_blank");else{$("generationText").textContent=r.message||"Preview generated by backend.";$("generationState").textContent="PREVIEW"}}catch(e){$("generationText").textContent="Preview endpoint unavailable.";$("generationState").textContent="UNAVAILABLE"}}
$("refresh").addEventListener("click",load);$("generate").addEventListener("click",generate);$("preview").addEventListener("click",preview);
$("downloadAll").addEventListener("click",async()=>{try{const d=await api("/reports/export?format=json");const blob=new Blob([JSON.stringify(d,null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="amcshield_report_export.json";a.click();URL.revokeObjectURL(u)}catch(e){$("generationText").textContent="Export endpoint unavailable."}});
$("menu").addEventListener("click",()=>{$("sidebar").classList.add("open");$("overlay").classList.add("show")});$("overlay").addEventListener("click",()=>{$("sidebar").classList.remove("open");$("overlay").classList.remove("show")});$("logout").addEventListener("click",()=>location.href="../login/index.html");load();
